### ISSUE TITLE
gst-resource-error-quark via homeassistant

### ISSUE THREAD

**Issue by tgurr** [happyleavesaoc/gstreamer-player#2]
I didn't want to hijack the other quark issue, but I also get this error, for me it is in combination with home assistant. When I try to play something via TTS i get the following error in the hass log:

`2017-08-16 18:45:37 ERROR (SyncWorker_0) [gsp] gst-resource-error-quark: Could not open resource for reading. (5)`

My hass configuration:

```
tts:
  - platform: picotts
    language: 'de-DE'

media_player:
  - platform: gstreamer
    name: 'tts'
    pipeline: 'audioresample ! audioconvert ! audio/x-raw,rate=48000,channels=2,format=S16LE ! wavenc ! filesink location=/tmp/snapfifo'
```

Playing from command line is working:
```
$ python3
Python 3.6.1 (default, Mar 28 2017, 16:46:16) 
[GCC 6.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from gsp import GstreamerPlayer
>>> player = GstreamerPlayer(None)
>>> player.queue("/home/user/testfiles/mpthreetest.mp3")
```

The snapcast fifo is there and the snapcast server<->client is working as well, for example if I use mpv to send something it plays just fine, e.g. with

`$ mpv mpthreetest.mp3 --audio-display=no --audio-channels=stereo --audio-samplerate=48000 --audio-format=s16 --ao=pcm --ao-pcm-file=/tmp/snapfifo`

And TTS over Snapcast also works fine on command line:

`$ pico2wave --lang=de-DE --wave=/tmp/test.wav "test 1 2 3 4 5" ; mpv /tmp/test.wav --audio-display=no --audio-channels=stereo --audio-samplerate=48000 --audio-format=s16 --ao=pcm --ao-pcm-file=/tmp/snapfifo`

Also plain gst-play-1.0 is working and it can play the wav file from pico2wave:
```
$ pico2wave --lang=de-DE --wave=/tmp/test.wav "test 1 2 3 4 5"
$ gst-play-1.0 /tmp/test.wav
```
What also works fine is sending the file to the fifo with the parameters used by the homeassistant pipeline:
`gst-launch-1.0 -v uridecodebin uri=file:///tmp/test.wav ! audioresample ! audioconvert ! audio/x-raw,rate=48000,channels=2,format=S16LE ! wavenc ! filesink location=/tmp/snapfifo`
